CREATE DATABASE pizzeria
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE USER 'pizza'@'localhost' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON *.* TO 'pizza'@'localhost' WITH GRANT OPTION;
CREATE USER 'pizza'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON *.* TO 'pizza'@'%' WITH GRANT OPTION;
